# SPDX-FileCopyrightText: 2009-2025 Sébastien Helleu <flashcode@flashtux.org>
#
# SPDX-License-Identifier: GPL-3.0-or-later

version = 1

[[annotations]]
path = [
    ".github/ISSUE_TEMPLATE/*.md",
    ".github/ISSUE_TEMPLATE/*.yml",
    ".gitignore",
    "CHANGELOG.md",
    "README.md",
    "requirements.txt",
    "tests/pwl*.txt",
]
precedence = "override"
SPDX-FileCopyrightText = "2009-2025 Sébastien Helleu <flashcode@flashtux.org>"
SPDX-License-Identifier = "GPL-3.0-or-later"

[[annotations]]
path = "tests/fr_invalid_utf8.po"
precedence = "override"
SPDX-FileCopyrightText = "2024-2025 Sébastien Helleu <flashcode@flashtux.org>"
SPDX-License-Identifier = "GPL-3.0-or-later"
